<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
            ['name' => 'Ahmad Saifudin Ardhiansyah', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 1],
            ['name' => 'Hananan Aflach Al-azizi', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 2],
            ['name' => 'Heppy Ratna Utami', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 3],
            ['name' => 'Humayra Delova Salsabila Putri', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 4],
            ['name' => 'Jerome Ocean Ferian Crystagana', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 5],
            ['name' => 'Achsan Fatchur Riskillah', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 6],
            ['name' => 'Ahmad Riky Wibisono Kurniawan', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 7],
            ['name' => 'Alvan Akbar Tazaqa Kurniawan', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 8],
            ['name' => 'Ananda Mareta Mallya Mas\'ud', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 9],
            ['name' => 'Arelleo Huan Anrico', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 10],
            ['name' => 'Arla', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 11],
            ['name' => 'Arseva Zanatu Anreka', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 12],
            ['name' => 'Cantik Nakesya Putri Kurniawan', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 13],
            ['name' => 'Delon Huwan Carlos Budiawan', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 14],
            ['name' => 'Deviadtul Azizah', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 15],
            ['name' => 'Dinda Biotica Almadya', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 16],
            ['name' => 'Donna Nazzila Kurmalasari', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 17],
            ['name' => 'Farhan Ilham Ramadhan', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 18],
            ['name' => 'Fatkur Nur Rohman Kurniawan', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 19],
            ['name' => 'Muhamad Rifaul Zaky', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 20],
            ['name' => 'Faza Risma Fadillah', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 21],
            ['name' => 'Geofanny Yoga Aflaha', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 22],
            ['name' => 'Jovanka Melody Alfare Rahmania', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 23],
            ['name' => 'Justine Queen Nadira Rizqitania Ferani', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 24],
            ['name' => 'Karina Putri Amalia', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 25],
            ['name' => 'Lexine Abdillah Harta Poetra', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 26],
            ['name' => 'Makayla Tania Hidayah', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 27],
            ['name' => 'Michelle Audrea Rizqitania Ferani', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 28],
            ['name' => 'Mohammad Tomy Kurniawan', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 29],
            ['name' => 'Muhammad Evan Harta Poetra', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 30],
            ['name' => 'Muhammad Febrian Valerino', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 31],
            ['name' => 'Muhammad Valentino Sandi', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 32],
            ['name' => 'Natasya Izza Pramudia', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 33],
            ['name' => 'Nindyta Melody Avriluno Rozy', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 34],
            ['name' => 'Radit', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 35],
            ['name' => 'Rama Wijaya Sagita Putra', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 36],
            ['name' => 'Rara Febyan Damayanti', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 37],
            ['name' => 'Rendi', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 38],
            ['name' => 'Restu Mahesa', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 39],
            ['name' => 'Ria Amalia Fauziah', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 40],
            ['name' => 'Richa Putri Azizah', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 41],
            ['name' => 'Ridwanto Fauzan', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 42],
            ['name' => 'Safinatunnajah As-syakirah(Arra)', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 43],
            ['name' => 'Sukma A\'dhom Puji Pamungkas', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 44],
            ['name' => 'Tasya Bella Adinda', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 45],
            ['name' => 'Tyas', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 46],
            ['name' => 'Viona Sagita Zalianty', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 47],
            ['name' => 'Yogi Akbarudin', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 48],
            ['name' => 'Yola Isadora Larasati', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 49],
            ['name' => 'Zygie Amanda Putri', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 50],
            ['name' => 'Riki Roman Firdaus', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 51],
            ['name' => 'Ahmad Rizki Aulia', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 52],
            ['name' => 'Yayan Hariadi', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 53],
            ['name' => 'Revan Indragunawan', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 54],
            ['name' => 'Talitha', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 55],
            ['name' => 'Meiko', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 56],
            ['name' => 'Ajay Fivedran Dede Agatha', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 57],
            ['name' => 'Stefano Wesley', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 58],
            ['name' => 'Ahmad Rizky Aulia', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 59],
            ['name' => 'Feni Ilma Hidayati', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 60],
            ['name' => 'Chika', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 61],
            ['name' => 'Lia', 'kelompok_id' => 2, 'is_active' => true, 'category_of_age' => 4, 'id' => 62],
            ['name' => 'Ana', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 63],
            ['name' => 'Anggun', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 64],
            ['name' => 'Ani', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 65],
            ['name' => 'Anip', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 66],
            ['name' => 'Arvin', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 67],
            ['name' => 'Aura', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 68],
            ['name' => 'Azhar', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 69],
            ['name' => 'Bella', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 70],
            ['name' => 'Bilal', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 71],
            ['name' => 'Caca', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 72],
            ['name' => 'Cinta', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 73],
            ['name' => 'Dito', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 74],
            ['name' => 'Erika', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 75],
            ['name' => 'Fahri', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 76],
            ['name' => 'Fajar', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 77],
            ['name' => 'Feren', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 78],
            ['name' => 'Ali Hisam', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 79],
            ['name' => 'Iis', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 80],
            ['name' => 'Ilham Fadhila(MT)', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 81],
            ['name' => 'Kevin Tirta Maulana', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 82],
            ['name' => 'Mery', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 83],
            ['name' => 'Nahel', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 84],
            ['name' => 'Nando', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 85],
            ['name' => 'Nesya', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 86],
            ['name' => 'Risky', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 87],
            ['name' => 'Sello', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 88],
            ['name' => 'Sidik', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 89],
            ['name' => 'Widy', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 90],
            ['name' => 'Yusi', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 91],
            ['name' => 'Zahwa', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 92],
            ['name' => 'Fadil', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 93],
            ['name' => 'Bebe', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 94],
            ['name' => 'Denis', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 95],
            ['name' => 'Ola Gino', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 96],
            ['name' => 'Ratu', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 97],
            ['name' => 'Yunus', 'kelompok_id' => 1, 'is_active' => true, 'category_of_age' => 4, 'id' => 98],
            ['name' => 'Fathul Romadon', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 99],
            ['name' => 'Afiza', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 100],
            ['name' => 'Alfin', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 101],
            ['name' => 'Aziz', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 102],
            ['name' => 'Andika', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 103],
            ['name' => 'Dini', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 104],
            ['name' => 'Fadli Umar', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 105],
            ['name' => 'Julian', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 106],
            ['name' => 'Lala', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 107],
            ['name' => 'Rahma', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 108],
            ['name' => 'Rama', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 109],
            ['name' => 'Risna', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 110],
            ['name' => 'Safa', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 111],
            ['name' => 'Sulthon', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 112],
            ['name' => 'Yogi', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 113],
            ['name' => 'Rafif Azzidan', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 114],
            ['name' => 'Wahyu Ubaidah(MT)', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 115],
            ['name' => 'Isharudin Ginona', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 116],
            ['name' => 'Lili', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 117],
            ['name' => 'Isna', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 118],
            ['name' => 'Cantika', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 119],
            ['name' => 'Akhyar', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 120],
            ['name' => 'Alia', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 121],
            ['name' => 'Alia', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 122],
            ['name' => 'Aliyantha Moh Berly Suhardian', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 123],
            ['name' => 'Dhio', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 124],
            ['name' => 'Diah Sastri', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 125],
            ['name' => 'Fadli', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 126],
            ['name' => 'Fendi', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 127],
            ['name' => 'Halil', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 128],
            ['name' => 'Lana', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 129],
            ['name' => 'M Nurhasim', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 130],
            ['name' => 'Putra Dirgantara', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 131],
            ['name' => 'Rizki Aditya', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 132],
            ['name' => 'Rizky (mt)', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 133],
            ['name' => 'Royan Aris Sudigno', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 134],
            ['name' => 'Sifa', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 135],
            ['name' => 'Ubai', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 136],
            ['name' => 'Wahyu Adji Setyo Nugroho', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 137],
            ['name' => 'Zaka Ahla dzikri', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 138],
            ['name' => 'Afian Bagus Frada S', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 139],
            ['name' => 'Affandi Ahmad Husaini', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 140],
            ['name' => 'Abdi', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 141],
            ['name' => 'Sandi Arya', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 142],
            ['name' => 'Dandi Cahyo', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 143],
            ['name' => 'Ilham Tri Biantoro', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 144],
            ['name' => 'Ica', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 145],
            ['name' => 'Taufiq', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 146],
            ['name' => 'Afifah', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 147],
            ['name' => 'Neneng', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 148],
            ['name' => 'Ahmad Aziz Setiawan Abdillah', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 149],
            ['name' => 'Zidan Alfaaza', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 150],
            ['name' => 'zaka Ahla dzikri', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 151],
            ['name' => 'Adit', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 152],
            ['name' => 'Karen', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 153],
            ['name' => 'Diah Alfatus', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 154],
            ['name' => 'Antra', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 155],
            ['name' => 'Ata', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 156],
            ['name' => 'Bila', 'kelompok_id' => 6, 'is_active' => true, 'category_of_age' => 4, 'id' => 157],
            ['name' => 'Muhammad Adji Suryanata', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 158],
            ['name' => 'Amron', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 159],
            ['name' => 'Devi', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 160],
            ['name' => 'Dewa', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 161],
            ['name' => 'Faza Ahsanul Rizky Wiyuda', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 162],
            ['name' => 'Kynan', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 163],
            ['name' => 'Mohammad Edo Abdulloh', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 164],
            ['name' => 'Nanda', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 165],
            ['name' => 'Nayla', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 166],
            ['name' => 'Muhammad Ravi Nurfirmansyah', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 167],
            ['name' => 'Satria Umar', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 168],
            ['name' => 'Uki', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 169],
            ['name' => 'Zulfikar', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 170],
            ['name' => 'Illyasa At Tariq (attar mt)', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 171],
            ['name' => 'Muhammad Fadilah Putra', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 172],
            ['name' => 'Muhammad Adam Prasetya', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 173],
            ['name' => 'Sava', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 174],
            ['name' => 'Herin Fauzan', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 175],
            ['name' => 'Gandi', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 176],
            ['name' => 'Faiz', 'kelompok_id' => 5, 'is_active' => true, 'category_of_age' => 4, 'id' => 177],
            ['name' => 'Ananuhi', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 178],
            ['name' => 'Dava Kharisma', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 179],
            ['name' => 'Dinda', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 180],
            ['name' => 'Gendis', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 181],
            ['name' => 'Husnia', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 182],
            ['name' => 'Lala', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 183],
            ['name' => 'Leonardo Geofany', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 184],
            ['name' => 'Lita', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 185],
            ['name' => 'M Anggara Afif A', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 186],
            ['name' => 'Mario Brossinanda', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 187],
            ['name' => 'Muhammad Aril F', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 188],
            ['name' => 'Muhammad Bagus Ichwanto', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 189],
            ['name' => 'Nicko Asaddulloh', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 190],
            ['name' => 'Nur Aini', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 191],
            ['name' => 'Raditya Noverdian saputra', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 192],
            ['name' => 'Ragil', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 193],
            ['name' => 'Revan Maulana Attalah', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 194],
            ['name' => 'Rifky Devlin Afnura', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 195],
            ['name' => 'Tegar Dewantara', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 196],
            ['name' => 'Zahra', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 197],
            ['name' => 'Zerli', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 198],
            ['name' => 'Razza', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 199],
            ['name' => 'Raynord', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 200],
            ['name' => 'Haitsuna Abdul Rozaq', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 201],
            ['name' => 'Keila Lovely Chantique W.', 'kelompok_id' => 7, 'is_active' => true, 'category_of_age' => 4, 'id' => 202],
            ['name' => 'Decka', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 203],
            ['name' => 'Bima', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 204],
            ['name' => 'Dinda', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 205],
            ['name' => 'Diva', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 206],
            ['name' => 'Hena', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 207],
            ['name' => 'Hendrik', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 208],
            ['name' => 'Hilma', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 209],
            ['name' => 'Ipan', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 210],
            ['name' => 'Kavita', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 211],
            ['name' => 'Melin', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 212],
            ['name' => 'Melinda', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 213],
            ['name' => 'Melisa', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 214],
            ['name' => 'Muhammad Raihan Majid', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 215],
            ['name' => 'Muhammad Yudistira Amanulloh', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 216],
            ['name' => 'Neo', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 217],
            ['name' => 'Nisa', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 218],
            ['name' => 'Ghozy', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 219],
            ['name' => 'Rosi', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 220],
            ['name' => 'Sabila', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 221],
            ['name' => 'Vina', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 222],
            ['name' => 'Wildan Rizki Mutrofin', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 223],
            ['name' => 'Muhammad Hasbi', 'kelompok_id' => 3, 'is_active' => true, 'category_of_age' => 4, 'id' => 224],
        ]);
    }
}
